# Generated by Django 5.1.1 on 2024-09-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
                ('p_name', models.CharField(max_length=50)),
                ('contactno', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_contact', models.IntegerField()),
                ('d_uname', models.CharField(max_length=25)),
                ('d_pwd', models.IntegerField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_contact', models.IntegerField()),
                ('p_age', models.IntegerField()),
                ('p_uname', models.CharField(max_length=25)),
                ('p_pwd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
